[package]
name = "bot-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = { version = "0.8.5", default-features = false, features = ["alloc"] }
rand_chacha = "0.3.1"
wasm-bindgen = "0.2.99"
