services:
  server:
    build: .

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tacticstoe-go.rule=Host(`tacticstoe-go.svrem.nl`)"
      - "traefik.http.routers.tacticstoe-go.entrypoints=websecure"
      - "traefik.http.routers.tacticstoe-go.tls.certresolver=myresolver"

    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}

      JWT_SECRET: ${JWT_SECRET}

    expose:
      - "8080"

networks:
  proxy:
    external: true
